language: generic
sudo: false
dist: trusty

notifications:
  email: false

addons:
  apt:
    packages:
      - libgmp-dev

env:
  global:
    - secure: "e3Bl8ND6N2ht7TIpR5ky8XgyLJYtyIUFn2tBc9mqFLDeFrbXI1lNSCllNC1x+cd6PIhGOBirqTYIhwt2fbj+4oXltESDfo5ON6uSXKOPYZO0Db6n8ImnVLN3mE7Z5mxUFdMFjVjAOU3MiQvDEr+vjFEQvX2wIWTWwARmHPj9TVu9wQqfvqwWo5oozPQGIeDZLkj43qm7USO4VlAVuil2sU/P7fmutoQsbK1q/QV2ctTEG9sTmWK+p1qQWNAJ03GLhYEhoUDK7dskSEU6/OiLxx1HGlmdZvTZUDoe52cr5Bvhslkke+2Ss3k81wcF7uvotsUzM/A7DB2ybI95VLLR3EzUI8b6bBAdsyJbFH8ux/HTuS8BYRML851nRVpMZMyPsAKPIOyPF1DfntiYUzjhGWfFIxOPSjETSYCFhVSYvArpX678uujXD/3BceGdyIDwQWLc/oAx8h3AH9H/T72u7mvLY/FqVuMO0NhJp1SeYUHTh4KT21XqNaJCKD4CTc9eVt/8n6aIEglO9IH8wZXwTTnwSzHPZgUr2U38X8aNFsPV8MnZ83v/HXg+phTAMKk6vRu+b/kT1X5GFh7QQxXFvtolJMBLPFpWINUeTcOO2ERqPV2QEyq0h/TdxJISE275IcMbh0GzTP3uFBSjl5IN+/45mWJTciD7BO/UF4fR8nY="

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack --no-terminal build --only-dependencies

script:
  - stack --no-terminal build

deploy:
  provider: script
  script: chmod +x ./deploy.sh && ./deploy.sh
  on:
    branch: source
  skip_cleanup: true

cache:
  directories:
    - $HOME/.stack
